export const modules = [
  {
    key: 'employee',
    name: 'Özlük & organizasyon',
    short: 'Özlük',
    icon: 'Users',
    description: 'Çalışan bilgileri, belgeler ve organizasyon yapısı tek bir yerde.',
    base: true,
  },
  {
    key: 'leave',
    name: 'İzin & fazla mesai',
    short: 'İzin',
    icon: 'CalendarDays',
    description: 'İzin bakiyeleri, ekip takvimi ve onay akışlarıyla planınız net olsun.',
  },
  {
    key: 'expense',
    name: 'Masraf & avans',
    short: 'Masraf',
    icon: 'Wallet',
    description: 'Harcama taleplerini toplayın, inceleyin ve onay süreçlerini hızlandırın.',
  },
  {
    key: 'attendance',
    name: 'PDKS & vardiya',
    short: 'PDKS',
    icon: 'Clock3',
    description: 'Giriş çıkışları, vardiyaları ve puantajı birlikte takip edin.',
  },
  {
    key: 'performance',
    name: 'Performans & hedefler',
    short: 'Performans',
    icon: 'Target',
    description: 'Hedefleri görünür kılın, gelişim görüşmelerini düzenli yürütün.',
  },
  {
    key: 'recruitment',
    name: 'İşe alım',
    short: 'İşe alım',
    icon: 'UserRoundPlus',
    description: 'Aday havuzundan işe girişe kadar tüm adımları takip edin.',
  },
  {
    key: 'payroll',
    name: 'Bordro',
    short: 'Bordro',
    icon: 'ReceiptText',
    description: 'Bordro operasyonunu ve çalışan ödeme bilgilerini yönetin.',
  },
  {
    key: 'assets',
    name: 'Zimmet',
    short: 'Zimmet',
    icon: 'Laptop',
    description: 'Ekipman teslimlerini, iadelerini ve çalışan zimmetlerini izleyin.',
  },
  {
    key: 'training',
    name: 'Eğitim',
    short: 'Eğitim',
    icon: 'GraduationCap',
    description: 'Eğitim planlarını, katılımı ve gelişim kayıtlarını bir araya getirin.',
  },
  {
    key: 'onboarding',
    name: 'İşe giriş',
    short: 'İşe giriş',
    icon: 'Sparkles',
    description: 'Yeni çalışma arkadaşlarınıza planlı ve sıcak bir başlangıç sunun.',
  },
  {
    key: 'announcements',
    name: 'Duyurular',
    short: 'Duyurular',
    icon: 'Megaphone',
    description: 'Şirket içi iletişimde herkes aynı bilgiye ulaşsın.',
  },
  {
    key: 'occupationalSafety',
    name: 'İş sağlığı & güvenliği',
    short: 'İSG',
    icon: 'ShieldCheck',
    description: 'İSG kayıtlarını ve operasyonel takip süreçlerini yönetin.',
  },
];
export const plans = [
  {
    key: 'starter',
    name: 'Başlangıç',
    audience: 'Temel İK süreçlerini düzene koyan ekipler',
    minimum: 10,
    modules: ['employee', 'leave', 'announcements'],
    features: [
      'Özlük ve organizasyon',
      'İzin & fazla mesai',
      'Şirket duyuruları',
      'Çalışan self servis',
      'Standart raporlar',
    ],
  },
  {
    key: 'growth',
    name: 'Büyüme',
    audience: 'Operasyonunu tek platformda birleştiren ekipler',
    minimum: 25,
    modules: [
      'employee',
      'leave',
      'expense',
      'attendance',
      'assets',
      'announcements',
      'onboarding',
    ],
    features: [
      'Başlangıç paketindeki her şey',
      'Masraf & avans yönetimi',
      'PDKS & vardiya planlama',
      'Zimmet ve işe giriş',
      'Modül bazlı genişleme',
    ],
  },
  {
    key: 'enterprise',
    name: 'Kurumsal',
    audience: 'Daha kapsamlı İK ihtiyaçları olan organizasyonlar',
    minimum: 50,
    modules: modules.map((m) => m.key),
    features: [
      'Tüm ürün modülleri',
      'Performans & işe alım',
      'Bordro, eğitim ve İSG',
      'Çok şirketli organizasyon',
      'Kuruma özel geçiş planı',
    ],
  },
];
export const moduleName = (key) => modules.find((m) => m.key === key)?.name ?? key;
export const planName = (key) => plans.find((p) => p.key === key)?.name ?? key;
